In [1]:
import pandas as pd
import re

# Load your DataFrame
df = pd.read_csv('C:\\Users\\Abdilala\\Documents\\GitHub\\EthioMart\\Task_1\\telegram_data.csv')

In [2]:
df

,Channel Title,Channel Username,ID,Message,Date,Media Path
0,Fashion tera,@Fashiontera,4059,NaN,2025-01-13 19:35:35+00:00,photos\@Fashiontera_4059.jpg
1,Fashion tera,@Fashiontera,4058,NaN,2025-01-11 19:36:42+00:00,photos\@Fashiontera_4058.jpg
2,Fashion tera,@Fashiontera,4057,〰️〰️〰️〰️〰️〰️〰️\nUnder Armur\nMade in Vietnam \...,2025-01-11 15:20:03+00:00,photos\@Fashiontera_4057.jpg
3,Fashion tera,@Fashiontera,4056,NaN,2025-01-11 15:20:03+00:00,photos\@Fashiontera_4056.jpg
4,Fashion tera,@Fashiontera,4054,NaN,2025-01-04 16:56:49+00:00,photos\@Fashiontera_4054.jpg
...,...,...,...,...,...,...
18918,EthioBrand®,@ethio_brand_collection,6,NaN,2017-07-07 10:44:35+00:00,photos\@ethio_brand_collection_6.jpg
18919,EthioBrand®,@ethio_brand_collection,5,NaN,2017-07-07 10:44:35+00:00,photos\@ethio_brand_collection_5.jpg
18920,EthioBrand®,@ethio_brand_collection,3,NaN,2017-07-07 10:44:35+00:00,photos\@ethio_brand_collection_3.jpg
18921,EthioBrand®,@ethio_brand_collection,2,NaN,2017-07-07 10:44:35+00:00,photos\@ethio_brand_collection_2.jpg
18922,EthioBrand®,@ethio_brand_collection,1,NaN,2017-07-07 10:27:14+00:00,NaN

In [3]:
print("Checking for NaN values in the 'Message' column:")
nan_count = df['Message'].isnull().sum()
print(f"Number of NaN values in 'Message' column: {nan_count}")

Checking for NaN values in the 'Message' column:
Number of NaN values in 'Message' column: 5910

In [4]:
df = df.dropna(subset=['Message'])

# Print the shape of the dataset after dropping NaN values in the "Message" column
print(f"Dataset shape after dropping NaN values in 'Message' column: {df.shape}")

Dataset shape after dropping NaN values in 'Message' column: (13013, 6)

In [5]:
df.head()

,Channel Title,Channel Username,ID,Message,Date,Media Path
2,Fashion tera,@Fashiontera,4057,〰️〰️〰️〰️〰️〰️〰️\nUnder Armur\nMade in Vietnam \...,2025-01-11 15:20:03+00:00,photos\@Fashiontera_4057.jpg
13,Fashion tera,@Fashiontera,4045,〰️〰️〰️〰️〰️〰️〰️\nMade in Vietnam \n🔸🔸🔸🔸🔸🔸\nSize...,2025-01-01 18:06:52+00:00,photos\@Fashiontera_4045.jpg
15,Fashion tera,@Fashiontera,4043,〰️〰️〰️〰️〰️〰️〰️\nNB\nMade in Vietnam \n🔸🔸🔸🔸🔸🔸\n...,2024-12-31 18:47:39+00:00,photos\@Fashiontera_4043.jpg
19,Fashion tera,@Fashiontera,4039,〰️〰️〰️〰️〰️〰️〰️\nHigh Quality shoes \n🔸🔸🔸🔸🔸🔸\nS...,2024-12-26 14:21:25+00:00,photos\@Fashiontera_4039.jpg
21,Fashion tera,@Fashiontera,4037,〰️〰️〰️〰️〰️ \nSkechers \nMade in Vietnam \n🔸🔸🔸🔸...,2024-12-24 13:42:02+00:00,photos\@Fashiontera_4037.jpg

In [6]:
message_df=df['Message']
message_df

2        〰️〰️〰️〰️〰️〰️〰️\nUnder Armur\nMade in Vietnam \...
13       〰️〰️〰️〰️〰️〰️〰️\nMade in Vietnam \n🔸🔸🔸🔸🔸🔸\nSize...
15       〰️〰️〰️〰️〰️〰️〰️\nNB\nMade in Vietnam \n🔸🔸🔸🔸🔸🔸\n...
19       〰️〰️〰️〰️〰️〰️〰️\nHigh Quality shoes \n🔸🔸🔸🔸🔸🔸\nS...
21       〰️〰️〰️〰️〰️ \nSkechers \nMade in Vietnam \n🔸🔸🔸🔸...
                               ...
18885    Ladies Nike \nMade in Vietnam\nSize 38\nPrice ...
18886    ፧ ተሽጦ አልቋል\nNike kobe 11\nMade in Vietnam\nSiz...
18887    Nike airmax flyknite\nMade in Vietnam\nSize 44...
18888    Nike airmax flyknite\nMade in Vietnam\nSize 42...
18889    Nike airmax tailwind \nMade in Vietnam\nSize 4...
Name: Message, Length: 13013, dtype: object

In [7]:

# Example of your DataFrame
# df = pd.DataFrame({'Message': ['💥3pcs silicon brush spatulas...', '💥Mandoline Slicer...', ...]})

# Define a function to remove emojis
def remove_emojis(text):
    emoji_pattern = re.compile(
        "[" 
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F700-\U0001F77F"  # alchemical symbols
        "\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
        "\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
        "\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
        "\U0001FA00-\U0001FA6F"  # Chess Symbols
        "\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
        "\U00002702-\U000027B0"  # Dingbats
        "\U000024C2-\U0001F251" 
        "]+", 
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

# Apply the function to the 'Message' column
df['Message'] = df['Message'].apply(remove_emojis)

# Display the updated DataFrame
print(df.head())

   Channel Title Channel Username    ID  \
2   Fashion tera     @Fashiontera  4057
13  Fashion tera     @Fashiontera  4045
15  Fashion tera     @Fashiontera  4043
19  Fashion tera     @Fashiontera  4039
21  Fashion tera     @Fashiontera  4037

                                              Message  \
2   \nUnder Armur\nMade in Vietnam \n\nSize    41,...
13  \nMade in Vietnam \n\nSize    42,43\nPrice   3...
15  \nNB\nMade in Vietnam \n\nSize    41,42,43\nPr...
19  \nHigh Quality shoes \n\nSize    43,44\nPrice ...
21   \nSkechers \nMade in Vietnam \n\nSize 40,42,4...

                         Date                    Media Path
2   2025-01-11 15:20:03+00:00  photos\@Fashiontera_4057.jpg
13  2025-01-01 18:06:52+00:00  photos\@Fashiontera_4045.jpg
15  2024-12-31 18:47:39+00:00  photos\@Fashiontera_4043.jpg
19  2024-12-26 14:21:25+00:00  photos\@Fashiontera_4039.jpg
21  2024-12-24 13:42:02+00:00  photos\@Fashiontera_4037.jpg

C:\Users\Abdilala\AppData\Local\Temp\ipykernel_13504\1963313681.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Message'] = df['Message'].apply(remove_emojis)

In [8]:
df.to_csv('clean_data.csv')

In [9]:
df

,Channel Title,Channel Username,ID,Message,Date,Media Path
2,Fashion tera,@Fashiontera,4057,"\nUnder Armur\nMade in Vietnam \n\nSize 41,...",2025-01-11 15:20:03+00:00,photos\@Fashiontera_4057.jpg
13,Fashion tera,@Fashiontera,4045,"\nMade in Vietnam \n\nSize 42,43\nPrice 3...",2025-01-01 18:06:52+00:00,photos\@Fashiontera_4045.jpg
15,Fashion tera,@Fashiontera,4043,"\nNB\nMade in Vietnam \n\nSize 41,42,43\nPr...",2024-12-31 18:47:39+00:00,photos\@Fashiontera_4043.jpg
19,Fashion tera,@Fashiontera,4039,"\nHigh Quality shoes \n\nSize 43,44\nPrice ...",2024-12-26 14:21:25+00:00,photos\@Fashiontera_4039.jpg
21,Fashion tera,@Fashiontera,4037,"\nSkechers \nMade in Vietnam \n\nSize 40,42,4...",2024-12-24 13:42:02+00:00,photos\@Fashiontera_4037.jpg
...,...,...,...,...,...,...
18885,EthioBrand®,@ethio_brand_collection,52,Ladies Nike \nMade in Vietnam\nSize 38\nPrice ...,2017-08-03 09:58:46+00:00,photos\@ethio_brand_collection_52.jpg
18886,EthioBrand®,@ethio_brand_collection,51,፧ ተሽጦ አልቋል\nNike kobe 11\nMade in Vietnam\nSiz...,2017-08-03 09:58:46+00:00,photos\@ethio_brand_collection_51.jpg
18887,EthioBrand®,@ethio_brand_collection,50,Nike airmax flyknite\nMade in Vietnam\nSize 44...,2017-08-03 09:58:46+00:00,photos\@ethio_brand_collection_50.jpg
18888,EthioBrand®,@ethio_brand_collection,49,Nike airmax flyknite\nMade in Vietnam\nSize 42...,2017-08-03 09:58:46+00:00,photos\@ethio_brand_collection_49.jpg
18889,EthioBrand®,@ethio_brand_collection,48,Nike airmax tailwind \nMade in Vietnam\nSize 4...,2017-08-03 09:58:45+00:00,photos\@ethio_brand_collection_48.jpg

In [10]:
import re

def label_message_utf8_with_birr(message):
    # Split the message at the first occurrence of '\n'
    if '\n' in message:
        first_line, remaining_message = message.split('\n', 1)
    else:
        first_line, remaining_message = message, ""
    
    labeled_tokens = []
    
    # Tokenize the first line
    first_line_tokens = re.findall(r'\S+', first_line)
    
    # Label the first token as B-PRODUCT and the rest as I-PRODUCT
    if first_line_tokens:
        labeled_tokens.append(f"{first_line_tokens[0]} B-PRODUCT")  # First token as B-PRODUCT
        for token in first_line_tokens[1:]:
            labeled_tokens.append(f"{token} I-PRODUCT")  # Remaining tokens as I-PRODUCT
    
    # Process the remaining message normally
    if remaining_message:
        lines = remaining_message.split('\n')
        for line in lines:
            tokens = re.findall(r'\S+', line)  # Tokenize each line while considering non-ASCII characters
            
            for token in tokens:
                # Check if token is a price (e.g., 500 ETB, $100, or ብር)
                if re.match(r'^\d{10,}$', token):
                    labeled_tokens.append(f"{token} O")  # Label as O for "other" or outside of any entity
                elif re.match(r'^\d+(\.\d{1,2})?$', token) or 'ETB' in token or 'ዋጋ' in token or '$' in token or 'ብር' in token:
                    labeled_tokens.append(f"{token} I-PRICE")
                # Check if token could be a location (e.g., cities or general location names)
                elif any(loc in token for loc in ['Addis Ababa', 'ለቡ', 'ለቡ መዳህኒዓለም', 'መገናኛ', 'ቦሌ', 'ሜክሲኮ']):
                    labeled_tokens.append(f"{token} I-LOC")
                # Assume other tokens are part of a product name or general text
                else:
                    labeled_tokens.append(f"{token} O")
    
    return "\n".join(labeled_tokens)

# Apply the updated function to the non-null messages
df['Labeled_Message'] = df['Message'].apply(label_message_utf8_with_birr)

# Display the updated DataFrame
df.head()

C:\Users\Abdilala\AppData\Local\Temp\ipykernel_13504\4257916439.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Labeled_Message'] = df['Message'].apply(label_message_utf8_with_birr)

,Channel Title,Channel Username,ID,Message,Date,Media Path,Labeled_Message
2,Fashion tera,@Fashiontera,4057,"\nUnder Armur\nMade in Vietnam \n\nSize 41,...",2025-01-11 15:20:03+00:00,photos\@Fashiontera_4057.jpg,Under O\nArmur O\nMade O\nin O\nVietnam O\nSiz...
13,Fashion tera,@Fashiontera,4045,"\nMade in Vietnam \n\nSize 42,43\nPrice 3...",2025-01-01 18:06:52+00:00,photos\@Fashiontera_4045.jpg,"Made O\nin O\nVietnam O\nSize O\n42,43 O\nPric..."
15,Fashion tera,@Fashiontera,4043,"\nNB\nMade in Vietnam \n\nSize 41,42,43\nPr...",2024-12-31 18:47:39+00:00,photos\@Fashiontera_4043.jpg,"NB O\nMade O\nin O\nVietnam O\nSize O\n41,42,4..."
19,Fashion tera,@Fashiontera,4039,"\nHigh Quality shoes \n\nSize 43,44\nPrice ...",2024-12-26 14:21:25+00:00,photos\@Fashiontera_4039.jpg,"High O\nQuality O\nshoes O\nSize O\n43,44 O\nP..."
21,Fashion tera,@Fashiontera,4037,"\nSkechers \nMade in Vietnam \n\nSize 40,42,4...",2024-12-24 13:42:02+00:00,photos\@Fashiontera_4037.jpg,Skechers O\nMade O\nin O\nVietnam O\nSize O\n4...

In [11]:
# Save the updated labeled dataset to a file in CoNLL format
labeled_data_birr_path = 'labeled_telegram_product_price_location.txt-'
with open(labeled_data_birr_path, 'w', encoding='utf-8') as f:
    for index, row in df.iterrows():
        f.write(f"{row['Labeled_Message']}\n\n")